/**
 * This is a hard-coded mapping of the ARA3 annotations to human readable name.
 *
 * This data is derived from http://api.brain-map.org/api/v2/structure_graph_download/1.json .
 *
 * TODO: We should write a parser for JSON ontologies.
 *
 */


export class MriAtlas {
    constructor() {
        console.log('MRI atlas created!');
    }

    public getNameForId(id: number) {
        return this.ara_id.has(id) ? this.ara_id.get(id) : 'UNKNOWN';
    }

    ara_id: Map<number, string> = new Map([
        [0, '0: Clear Label'],
        [1, '1: descending corticofugal pathways'],
        [2, '2: substantia nigra'],
        [3, '3: subthalamic nucleus'],
        [4, '4: molecular layer of the cerebellum'],
        [5, '5: granule cell level of the cerebellum'],
        [6, '6: alveus of the hippocampus'],
        [7, '7: inferior cerebellar peduncle'],
        [10, '10: cingulate cortex, area 2'],
        [30, '30: striatum'],
        [31, '31: globus pallidus'],
        [32, '32: entopeduncular nucleus'],
        [33, '33: ventricular system'],
        [34, '34: medial lemniscus'],
        [35, '35: facial nerve'],
        [36, '36: anterior commissure, anterior part'],
        [37, '37: anterior commissure, posterior part'],
        [38, '38: ventral hippocampal commissure'],
        [39, '39: thalamus'],
        [40, '40: septal region'],
        [41, '41: optic nerve'],
        [42, '42: optic tract and optic chiasm'],
        [43, '43: pineal gland'],
        [45, '45: spinal cord'],
        [46, '46: commissure of the superior colliculus'],
        [47, '47: brainstem'],
        [48, '48: hypothalamic region'],
        [50, '50: superficial gray layer of the superior colliculus'],
        [51, '51: periaqueductal gray'],
        [52, '52: fornix'],
        [53, '53: mammillothalamic tract'],
        [54, '54: commissural stria terminalis'],
        [55, '55: deeper layers of the superior colliculus'],
        [56, '56: periventricular gray'],
        [57, '57: genu of the facial nerve'],
        [58, '58: pontine nuclei'],
        [59, '59: fimbria of the hippocampus'],
        [60, '60: fasciculus retroflexus'],
        [61, '61: stria medullaris of the thalamus'],
        [62, '62: stria terminalis'],
        [63, '63: posterior commissure'],
        [64, '64: glomerular layer of the accessory olfactory bulb'],
        [65, '65: glomerular layer of the olfactory bulb'],
        [66, '66: olfactory bulb'],
        [67, '67: corpus callosum and associated subcortical white matter'],
        [68, '68: brachium of the superior colliculus'],
        [69, '69: inferior colliculus, commissure'],
        [70, '70: central canal'],
        [71, '71: interpeduncular nucleus'],
        [72, '72: ascending fibers of the facial nerve'],
        [73, '73: anterior commissure'],
        [74, '74: inferior olive'],
        [75, '75: spinal trigeminal nucleus'],
        [76, '76: spinal trigeminal tract'],
        [77, '77: frontal association cortex'],
        [78, '78: middle cerebellar peduncle'],
        [79, '79: transverse fibers of the pons'],
        [80, '80: habenular commissure'],
        [81, '81: nucleus of the stria medullaris'],
        [82, '82: basal forebrain region'],
        [83, '83: supraoptic decussation'],
        [84, '84: medial lemniscus decussation'],
        [85, '85: pyramidal decussation'],
        [92, '92: neocortex'],
        [93, '93: bed nucleus of the stria terminalis'],
        [94, '94: pretectal region'],
        [95, '95: cornu ammonis 3'],
        [96, '96: dentate gyrus'],
        [97, '97: cornu ammonis 2'],
        [98, '98: cornu ammonis 1'],
        [99, '99: fasciola cinereum'],
        [100, '100: subiculum'],
        [108, '108: postrhinal cortex'],
        [109, '109: presubiculum'],
        [110, '110: parasubiculum'],
        [112, '112: perirhinal area 35'],
        [113, '113: perirhinal area 36'],
        [114, '114: entorhinal cortex'],
        [115, '115: lateral entorhinal cortex'],
        [119, '119: vestibular apparatus'],
        [120, '120: cochlea'],
        [121, '121: cochlear nerve'],
        [122, '122: vestibular nerve'],
        [123, '123: ventral cochlear nucleus, granule cell layer'],
        [125, '125: 4th ventricle'],
        [126, '126: dorsal cochlear nucleus, molecular layer'],
        [127, '127: dorsal cochlear nucleus, fusiform and granule layer'],
        [128, '128: dorsal cochlear nucleus, deep core'],
        [129, '129: acoustic striae'],
        [130, '130: trapezoid body'],
        [131, '131: nucleus of the trapezoid body'],
        [132, '132: superior paraolivary nucleus'],
        [133, '133: medial superior olive'],
        [134, '134: lateral superior olive'],
        [135, '135: superior periolivary region'],
        [136, '136: ventral periolivary nuclei'],
        [137, '137: lateral lemniscus, ventral nucleus'],
        [138, '138: lateral lemniscus, intermediate nucleus'],
        [139, '139: lateral lemniscus, dorsal nucleus'],
        [140, '140: lateral lemniscus, commissure'],
        [141, '141: lateral lemniscus'],
        [142, '142: inferior colliculus, dorsal cortex'],
        [143, '143: inferior colliculus, central nucleus'],
        [145, '145: inferior colliculus, external cortex'],
        [146, '146: inferior colliculus, brachium'],
        [147, '147: medial geniculate body, medial division'],
        [148, '148: medial geniculate body, dorsal division'],
        [149, '149: medial geniculate body, ventral division'],
        [150, '150: medial geniculate body, marginal zone'],
        [151, '151: primary auditory cortex'],
        [152, '152: secondary auditory cortex, dorsal area'],
        [153, '153: secondary auditory cortex, ventral area'],
        [157, '157: auditory radiation'],
        [158, '158: ventral cochlear nucleus, anterior part'],
        [159, '159: ventral cochlear nucleus, posterior part'],
        [160, '160: ventral cochlear nucleus, cap area'],
        [162, '162: spiral ganglion'],
        [163, '163: nucleus sagulum'],
        [164, '164: reticular thalamic nucleus, auditory segment']
    ]);

}