stages:
  - test
  - deploy
language: python
os:
  - linux
python:
  - "2.7"
  - "3.5"
jobs:
  include:
    - stage: test
      name: "C++"
      language: cpp
      install:
        - cd python
        - mkdir build
      script:
        - cd build
        - cmake ..
        - make
        - ctest
    - stage: test
      language: python
      os: osx
      osx_image: xcode8.3
      python: "3.6-dev"
    - stage: deploy
      name: "nodejs_build_and_deploy"
      language: node_js
      group: travis_lts
      addons:
        chrome: stable
      sudo: required
      node_js:
      - 9.2.1
      cache:
        directories:
        - node_modules
      before_install:
      - openssl aes-256-cbc -K $encrypted_f46babd475e4_key -iv $encrypted_f46babd475e4_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
      - tar -xzf credentials.tar.gz
      - sudo mv secrets /secrets && sudo chown $USER /secrets
      - rm credentials.tar.gz
      - $(python version.py) #sets APPVERSION
      install:
      - echo "prevent running npm install twice"
      script:
      - npm install
      #- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9876 http://localhost &
      #- npm run test
      after_success:
      - sudo apt-get -qq update;
      - sudo apt-get install -y oracle-java8-set-default
      - npm run build-python-min
      - cp -r ./dist/python-min appengine/frontend/static/
      deploy:
      - provider: gae
        skip_cleanup: true
        keyfile: "/secrets/google-secret.json"
        project: neuromancer-seung-import
        version: "$APPVERSION"
        on:
          all_branches: true
        no_promote: true
        default: true
        verbosity: error
        config: "./appengine/frontend/app.yaml"
        no_stop_previous_version: false
install:
  - pip install tox-travis
script:
  - cd python
  - tox -vvvvvvv
